cryptog = ['DARUSDT', 'BNXUSDT', 'CELRUSDT',
'CTSIUSDT', 'LTCUSD', 'MANAUSD', 'FXSUSDT', 'ICXUSDT', 'XCNUSDT', 'AAVEUSDT', 'BELUSDT', 'LITUSDT',
'RENUSDT', 'SUSHIUSDT', 'XRPUSD	', 'DOTUSD', 'BLZUSDT', 'TRXUSDT', 'GLMRUSDT',
'STGUSDT', 'SPELLUSDT', 'CTCUSDT', 'APEUSDC', 'RSS3USDT', '1000XECUSDT', 'MANAUSDT', 'ADAUSD', 'ILVUSDT', 'MTLUSDT',
'HOTUSDT', 'FILUSDT', 'C98USDT', 'BOBAUSDT', 'NEOUSDT', 'SKLUSDT', 'FLMUSDT', '1000BTTUSDT', 'LDOUSDT', 'ZECUSDT',
'OGNUSDT', 'DOGEUSDT', 'ONTUSDT', 'SOLUSD', 'GMTUSDC', 'GALAUSDT', 'KAVAUSDT', '10000NFTUSDT', 'SLPUSDT', 'LRCUSDT',
'SANDUSDC', 'TRBUSDT', 'OCEANUSDT', 'CRVUSDT', 'KDAUSDT', 'BITUSD', 'BALUSDT', 'SCRTUSDT', 'API3USDT', 'NEARUSDT']
# '', '', '', '', '', '', '', '', '', '',
# '', '', '', '', '', '', '', '', '', ''
